### PR TITLE
Starter corpus

### PR DESCRIPTION
**Pull request by eseiver**
This renames the seed corpus to starter corpus, a slightly nicer name. It also adds its location to the `__init__` file so it can be easily found.

### CODE REVIEW

**Comment by sbassi** [comment]
I tried to run this version and I got an error:

(eliz) sbassi@Us-IT00354:~/projects/plos/eliz/allofplos$ python -m allofplos.plos_corpus
Not enough articles in corpusdir, re-downloading zip file
Traceback (most recent call last):
  File "/home/sbassi/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sbassi/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sbassi/projects/plos/eliz/allofplos/allofplos/plos_corpus.py", line 822, in <module>
    main()
  File "/home/sbassi/projects/plos/eliz/allofplos/allofplos/plos_corpus.py", line 796, in main
    create_local_plos_corpus()
  File "/home/sbassi/projects/plos/eliz/allofplos/allofplos/plos_corpus.py", line 720, in create_local_plos_corpus
    unzip_articles(file_path=zip_path)
  File "/home/sbassi/projects/plos/eliz/allofplos/allofplos/plos_corpus.py", line 689, in unzip_articles
    with zipfile.ZipFile(file_path, "r") as zip_ref:
  File "/home/sbassi/anaconda3/lib/python3.6/zipfile.py", line 1100, in __init__
    self._RealGetContents()
  File "/home/sbassi/anaconda3/lib/python3.6/zipfile.py", line 1167, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Also, somehow related, the method download_file_from_google_drive in the documentation is says it returns None, but it actually returns something. This is not the root cause of the problem, but you could change the docstring while fixing this.

**Comment by sbassi** [comment]
Wait. I know what is going on. I had a bad zip file there as a product of a previous unsuccessful download. So I deleted and I am trying again.

**Comment by sbassi** [comment]
so forget about this, but the docstring error on download_file_from_google_drive can be fixed anyway:

**Comment by eseiver** [comment]
updated the docstring!

**Comment by sbassi** [comment]
There is something else I found: Both starter_corpus and seed_corpus directories are present now. seed_corpus and its content (an init file) should be deleted.

**Comment by eseiver** [comment]
Thanks for catching that. Fixed.

**Pull request merged**
