### PR TITLE
Pretty articles

### PR DESCRIPTION
**Pull request by mpacer**
This provides a prettier way to display Articles when in the jupyter notebook, see image below.

The article's title links to the plos webpage, the doi links to the doi.org webpage.

image

You don't _want_ to know how long it took to get the title to align properly…`inline-flex` for the win.

### CODE REVIEW

**Comment by sbassi** [comment]
This feature is worth mentioning in the paper, it could be next to the mention to the Jupyter notebook example. See PR #62

**Comment by mpacer** [comment]
Agreed, but I still think we need a lot better docs before we come anywhere near submitting a JOSS paper. 

But it should also definitely make its way into the scipy paper assuming that the proposal gets accepted (along with the design principles for the stuff in #89).

**Comment by mpacer** [comment]
I cannot figure out why github is ordering those in the way that it is since this is my log…

anyway the utils bit is necessary for the `_repr_html_` to work so i'll just squash that.

```
(dev) ~/jupyter/allofplos pretty_articles$ git log --oneline |head
46ce8a2 checks if back exists before indexing into it; fixes #90
dde54fe Add utils module for the dedent method  & home for future utilities
0430712 add pretty _repr_html_ to article to make links when displayed in notebook
a36d836 move article_class.py to article.py; update imports
97381ca Merge pull request #83 from sbassi/subjectsDB
```

**Comment by eseiver** [comment]
LGTM. Rebased on master, all tests passing

**Pull request merged**
