### PR TITLE
Articles in corpus

### PR DESCRIPTION
**Pull request by mpacer**
Introduces a bunch of new utilities to the Corpus class. 

Including

`len(Corpus())` to get the number of articles.

`for article in Corpus()` to iterate through articles.

`Corpus.random_article` to get one random article. 

It also has a new tutorial documenting how to use it, creating the `docs/source` folders to house said tutorial.

In a later PR, I will hook this up to proper docs machinery.

### CODE REVIEW

**Comment by mpacer** [comment]
Now this also adds a seed argument to the Corpus `__init__` in order to ensure better reproducibility for testing.

**Comment by eseiver** [comment]
Do we want to remove user need to access Article all-together? Can we make a `from_doi` method for when people want a specific article and not to iterate?

**Comment by mpacer** [comment]
I can do you one better!

**Comment by eseiver** [comment]
also:
- what is easiest way to iterate through e.g. the first 100 DOIs, or get a subset of the corpus? `random_article`? Noticed you can't do [:100].
- for cell [8] in the Notebook, could you highlight Article properties instead? maybe .journal, .pubdate?

**Comment by mpacer** [comment]
with ef8a923 you can access an item in a corpus using dictionary-like key access.

For example:
```
corpus['10.1371/journal.pcbi.1004141']
```

**Comment by mpacer** [comment]
> for cell [8] in the Notebook, could you highlight Article properties instead? maybe .journal, .pubdate?

I did that to satisfy your request, but I strongly disagree with it.

I think the Article properties should be handled in a separate `Article` tutorial, this tutorial should stop at showing how to use `Corpus` not how to use the `Article`s you get from `Corpus`.

**Comment by mpacer** [comment]
I rebased to first move the file and then make all of the changes so that the changes would be picked up in the git history as the most recent changes.

**Pull request merged**
